### ISSUE TITLE
Unit in uammd

### ISSUE THREAD

**Issue by mliyuanjie** [RaulPPelaez/UAMMD#22]
Thanks for the nice lib, I am confusing what is the unit each parameters, forexpamle, the viscosity, radisu, box...

**Comment by RaulPPelaez** [comment]
Hi! UAMMD does not have any unit subsystem. Whatever you provide will be respected.
See for instance here https://uammd.readthedocs.io/en/latest/Integrator/BrownianDynamics.html#brownian-dynamics
The equations solved by this module are laid out in the top, the parameters you provide when creating it are directly the ones appearing in the equation.

**Comment by mliyuanjie** [comment]
> Hi! UAMMD does not have any unit subsystem. Whatever you provide will be respected. See for instance here https://uammd.readthedocs.io/en/latest/Integrator/BrownianDynamics.html#brownian-dynamics The equations solved by this module are laid out in the top, the parameters you provide when creating it are directly the ones appearing in the equation.

Great Thanks a lot. works very well, excellent project.
